## Example config for integration testing

nmesos_version: '0.0.12' ## Min nmesos required to execute this config

common:

  resources:
    instances: 1 # Initial number of instances (This will auto scale up and down to SPREAD_ALL_SLAVES)
    cpus: 0.1
    memoryMb: 50

  container:
    network: HOST            # Optional parameter the default is Bridge
    image:  gonitro/sidecar  # Docker repo/image without the tag
    #forcePullImage: true                    # Optional to force pull (default false)

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   #  (HOST:CONTAINER) with default rw or (HOST:CONTAINER:rw)

    labels:
      SidecarDiscover: "false"

    env_vars:
      SIDECAR_SEEDS: 127.0.0.1
      SIDECAR_LOGGING_LEVEL: info


    dockerParameters: ## Optional extra parameters in addition to labels and env_vars
      cap-add: NET_ADMIN

  singularity:
    deployInstanceCountPerStep: 1   # Number of instances deployed at once.
    autoAdvanceDeploySteps: true    # false to have Canary deployments.
    deployStepWaitTimeMs: 1000      # Time to wait between deployments
    slavePlacement: "SPREAD_ALL_SLAVES" # Ignore num instances and auto scale up/down to all nodes
    requiredRole: "OPS"            # Only use reserved resources with this role

environments:
  dev:
    singularity:
      url: "http://localhost:7099/singularity"
