nmesos_version: '0.2.10' ## Min nmesos required to execute this config

common:

  resources:
    instances: 1 # Number of instances to deploy
    cpus: 0.1
    memoryMb: 128

  container:

    image: nginx # Docker repo/image without the tag

    ports:
      - 80

    labels:

    env_vars:
    #NEW_RELIC_LICENSE_KEY: "xxxxx"
    #JAVA_OPTS: -Xmx64m

  singularity:
    deployInstanceCountPerStep: 1   # Number of instances deployed at once.
    autoAdvanceDeploySteps: true    # false to have Canary deployments.
    deployStepWaitTimeMs: 1000      # Time to wait between deployments
    healthcheckUri: "/"             # Used for singularity to determine if a deploy was success


environments:
  dev:
    singularity:
      url: "http://localhost:7099/singularity"

    ## Optional configuration to define a job to deploy after this job
    after_deploy:
      on_success:
        - service_name: "cli/src/it/resources/config/example-deploy-chain-service-real-1"
        - service_name: "cli/src/it/resources/config/example-deploy-chain-service-real-2"
          tag: "alpine"

      on_failure:
        service_name: "cli/src/it/resources/config/example-deploy-chain-service-real-failure"
        tag: "latest"
