name: Nmesos

on:
  pull_request:
  push:
    branches:
    - trunk

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"

    - name: Test
<<<<<<< HEAD
      run: sbt nmesos-shared/test nmesos-cli/test
=======
      run: sbt test
>>>>>>> Make CI/CD work (Github Actions).

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: nmesos
        SLACK_MESSAGE: 'Test success'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
